# Nome do arquivo fonte e do executável
SRC = pratica3b.cpp
EXEC = pratica3b.exe

# Regra padrão para compilar, linkar e executar
all: $(EXEC)

$(EXEC):
	g++ -o $(EXEC) $(SRC) -I"C:\Program Files\Common Files\MinGW\freeglut\include" -L"C:\Program Files\Common Files\MinGW\freeglut\lib" -lfreeglut -lopengl32 -lglu32

run: clean all
	./$(EXEC)

clean:
	del $(EXEC)